steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - make_new_order
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
  - --entry-point=get_order